#!/usr/bin/env bash
# Generate prod_setup_bundle.sql: the full from-scratch database setup for a FRESH
# Supabase project, concatenated in dependency order so it can be pasted and run as a
# single batch in the SQL editor. The bundle is a GENERATED artifact (gitignored);
# this script is the source of truth, so the bundle can never drift from the SQL files.
#
# Order: schema.sql (base, 16 tables) then supabase-setup.sql (closed_trades, error_log,
# indexes) then api/migrations/002..024 (features + atomic cash/trade RPCs). Verified
# safe to paste as ONE script: no psql meta-commands, no CREATE INDEX CONCURRENTLY, no
# explicit BEGIN/COMMIT. Every statement is guarded (IF NOT EXISTS / IF EXISTS / OR
# REPLACE), so the whole thing is safe to re-run.
#
# After running it in Supabase, verify with:  node tests/_schema_check.mjs  (prod .env)
#
# Usage: bash scripts/build_setup_bundle.sh
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$ROOT/prod_setup_bundle.sql"

{
  echo "-- ============================================================================"
  echo "-- OUTPOST PRODUCTION DATABASE SETUP (GENERATED by scripts/build_setup_bundle.sh)"
  echo "-- Do not edit by hand. Paste this ENTIRE file into the Supabase SQL editor of a"
  echo "-- FRESH project and click Run. Order: schema.sql, supabase-setup.sql, then every"
  echo "-- migration 002..024. Every statement is guarded, so it is safe to re-run."
  echo "-- Verify afterward with:  node tests/_schema_check.mjs   (prod creds in .env)"
  echo "-- ============================================================================"
  echo ""

  for f in schema.sql supabase-setup.sql; do
    echo ""
    echo "-- ==================== FILE: $f ===================="
    echo ""
    cat "$ROOT/$f"
  done

  for f in "$ROOT"/api/migrations/*.sql; do
    echo ""
    echo "-- ==================== FILE: api/migrations/$(basename "$f") ===================="
    echo ""
    cat "$f"
  done
} > "$OUT"

migs=$(ls -1 "$ROOT"/api/migrations/*.sql | wc -l | tr -d ' ')
echo "Wrote $OUT ($(wc -l < "$OUT" | tr -d ' ') lines from $((migs + 2)) SQL files)."
