/**
 * Catalyst Watch — "On Deck" feature.
 *
 * 3 timed drops per day:
 *   9:15 AM ET  — Pre-Market Catalyst Watch (overnight earnings, analyst upgrades, breaking news)
 *   12:00 PM ET — Midday Movers (morning news cycle, analyst actions, social buzz shifts)
 *   3:30 PM ET  — Power Hour Watch (tonight's earnings, late-breaking news, momentum)
 *
 * Each drop: 3 stocks with catalyst reasons + strength rating (1-3 flames).
 * End-of-day recap shows how picks performed.
 */
import express from 'express';
import Anthropic from '@anthropic-ai/sdk';
import { supabase } from '../db.js';
import { requireAuth } from '../middleware/auth.js';
import { rateLimit } from '../middleware/rateLimit.js';
import { getSnapshots } from '../utils/polygon.js';
import {
  getEarningsCalendar,
  getBreakingNews,
  getTickerNews,
  getUpgradeDowngrade,
  isFinnhubAvailable,
} from '../utils/finnhub.js';
import { memGet, memSet } from '../services/memoryCache.js';
import { getMarketData } from '../services/marketData.js';
import { config } from '../config.js';

const router = express.Router();
const anthropic = new Anthropic({ apiKey: config.anthropicKey });
const MODEL_HAIKU = 'claude-haiku-4-5-20251001';

// Drop schedule in ET (Eastern Time)
const DROP_SCHEDULE = [
  { id: 'premarket',  label: 'Pre-Market Catalyst Watch', hour: 9,  minute: 15 },
  { id: 'midday',     label: 'Midday Movers',             hour: 12, minute: 0  },
  { id: 'powerhour',  label: 'Power Hour Watch',          hour: 15, minute: 30 },
];

// In-memory store for today's catalyst data
let catalystDrops = {};  // { premarket: { stocks: [...], generatedAt, label }, ... }
let catalystDay = null;  // Track current day for midnight reset
let recapData = null;    // End of day recap

/**
 * Get current ET time info
 */
function getETTime() {
  const now = new Date();
  const etStr = now.toLocaleString('en-US', { timeZone: 'America/New_York' });
  const et = new Date(etStr);
  return {
    now: et,
    hour: et.getHours(),
    minute: et.getMinutes(),
    dateStr: now.toISOString().split('T')[0],
    dayOfWeek: et.getDay(), // 0=Sun, 6=Sat
    timeStr: et.toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit', hour12: true }),
  };
}

/**
 * Determine which drops should have been generated by now
 */
function getActiveDropIds(hour, minute) {
  return DROP_SCHEDULE
    .filter(d => hour > d.hour || (hour === d.hour && minute >= d.minute))
    .map(d => d.id);
}

/**
 * Gather catalyst candidates for a specific drop window.
 * Each window has different data emphasis.
 */
async function gatherCandidates(dropId) {
  const candidates = [];
  const sources = { earnings: false, news: false, upgrades: false };

  try {
    const today = new Date().toISOString().split('T')[0];
    const tomorrow = new Date(Date.now() + 86400000).toISOString().split('T')[0];

    // Always fetch earnings calendar and breaking news
    const [earningsResult, newsResult] = await Promise.allSettled([
      getEarningsCalendar(today, tomorrow),
      getBreakingNews(20),
    ]);
    const earnings = earningsResult.status === 'fulfilled' ? earningsResult.value : [];
    const news = newsResult.status === 'fulfilled' ? newsResult.value : [];
    sources.earnings = earningsResult.status === 'fulfilled' && earnings.length > 0;
    sources.news = newsResult.status === 'fulfilled' && news.length > 0;

    if (dropId === 'premarket') {
      // Focus: overnight earnings reactions, pre-market analyst notes, breaking overnight news

      // Stocks that reported after close yesterday (epsActual exists = already reported)
      const reportedLastNight = earnings.filter(e => e.date === today && e.hour === 'bmo' && e.epsActual != null);
      for (const e of reportedLastNight.slice(0, 8)) {
        const beat = e.epsActual > e.epsEstimate;
        candidates.push({
          ticker: e.ticker,
          catalystType: 'earnings_reaction',
          catalystLabel: 'EARNINGS',
          detail: `Reported Q${e.quarter} earnings ${beat ? 'BEAT' : 'MISS'}: $${e.epsActual} EPS vs $${e.epsEstimate} est.`,
          strength: beat ? 2 : 1,
        });
      }

      // Stocks reporting before market open today
      const reportingBMO = earnings.filter(e => e.date === today && e.hour === 'bmo' && e.epsActual == null);
      for (const e of reportingBMO.slice(0, 8)) {
        candidates.push({
          ticker: e.ticker,
          catalystType: 'earnings_upcoming',
          catalystLabel: 'REPORTS TODAY',
          detail: `Reports earnings before market open. EPS est: $${e.epsEstimate ?? 'N/A'}.`,
          strength: 2,
        });
      }

      // Stocks reporting after close today (set up for the day)
      const reportingAMC = earnings.filter(e => e.date === today && e.hour === 'amc');
      for (const e of reportingAMC.slice(0, 5)) {
        candidates.push({
          ticker: e.ticker,
          catalystType: 'earnings_tonight',
          catalystLabel: 'REPORTS TONIGHT',
          detail: `Reports Q${e.quarter} earnings after close. EPS est: $${e.epsEstimate ?? 'N/A'}.`,
          strength: 1,
        });
      }

    } else if (dropId === 'midday') {
      // Focus: morning news cycle, analyst actions from today, social buzz

      // Stocks reporting after close tonight (building anticipation)
      const reportingTonight = earnings.filter(e => e.date === today && e.hour === 'amc');
      for (const e of reportingTonight.slice(0, 5)) {
        candidates.push({
          ticker: e.ticker,
          catalystType: 'earnings_tonight',
          catalystLabel: 'REPORTS TONIGHT',
          detail: `Reports Q${e.quarter} earnings after close. EPS est: $${e.epsEstimate ?? 'N/A'}.`,
          strength: 2,
        });
      }

    } else if (dropId === 'powerhour') {
      // Focus: tonight's after-hours earnings, late news, setup for tomorrow

      // Stocks reporting after close (primary catalyst for power hour)
      const reportingTonight = earnings.filter(e => e.date === today && e.hour === 'amc');
      for (const e of reportingTonight.slice(0, 8)) {
        candidates.push({
          ticker: e.ticker,
          catalystType: 'earnings_tonight',
          catalystLabel: 'REPORTS TONIGHT',
          detail: `Reports Q${e.quarter} earnings after close tonight. EPS est: $${e.epsEstimate ?? 'N/A'}.`,
          strength: 3,
        });
      }

      // Tomorrow's before-market-open reporters (setup overnight holds)
      const tomorrowBMO = earnings.filter(e => e.date === tomorrow && e.hour === 'bmo');
      for (const e of tomorrowBMO.slice(0, 5)) {
        candidates.push({
          ticker: e.ticker,
          catalystType: 'earnings_tomorrow',
          catalystLabel: 'REPORTS TOMORROW',
          detail: `Reports earnings before open tomorrow. EPS est: $${e.epsEstimate ?? 'N/A'}.`,
          strength: 1,
        });
      }
    }

    // For ALL drops: extract tickers mentioned in breaking news headlines
    const tickerPattern = /\b([A-Z]{2,5})\b/g;
    const newsTickerCounts = {};
    for (const article of news) {
      const text = article.title + ' ' + article.summary;
      const matches = text.match(tickerPattern) || [];
      for (const m of matches) {
        // Filter out common words that look like tickers
        if (['THE','FOR','AND','NOT','BUT','CEO','CFO','IPO','FDA','SEC','ETF','GDP','CPI','FED'].includes(m)) continue;
        newsTickerCounts[m] = (newsTickerCounts[m] || 0) + 1;
      }
    }
    // Add news-mentioned tickers not already in candidates
    const existingTickers = new Set(candidates.map(c => c.ticker));
    const newsMentioned = Object.entries(newsTickerCounts)
      .filter(([ticker]) => !existingTickers.has(ticker))
      .sort((a, b) => b[1] - a[1])
      .slice(0, 5);

    for (const [ticker, count] of newsMentioned) {
      // Find the relevant news headline
      const relevantArticle = news.find(n => (n.title + ' ' + n.summary).includes(ticker));
      if (relevantArticle) {
        candidates.push({
          ticker,
          catalystType: 'news',
          catalystLabel: 'BREAKING NEWS',
          detail: relevantArticle.title,
          strength: count >= 3 ? 2 : 1,
        });
      }
    }

  } catch (err) {
    console.error(`[Catalyst] Candidate gathering failed for ${dropId}:`, err.message);
  }

  // Determine data quality
  const sourceCount = Object.values(sources).filter(Boolean).length;
  const quality = sourceCount >= 2 ? 'full' : sourceCount === 1 ? 'partial' : 'degraded';

  return { candidates, quality, sources };
}

/**
 * Use Claude to score and select the top 3 candidates for a drop.
 * The AI considers catalyst quality, market relevance, and actionability.
 */
async function scoreCandidates(candidates, dropId, dropLabel) {
  if (candidates.length <= 3) {
    // Not enough candidates to need AI scoring, just enrich and return
    return candidates.slice(0, 3);
  }

  try {
    const candidateStr = candidates.map((c, i) =>
      `${i + 1}. ${c.ticker} | Type: ${c.catalystType} | Label: ${c.catalystLabel} | Detail: ${c.detail} | Strength: ${c.strength}/3`
    ).join('\n');

    // Get market regime for context-aware scoring
    const market = getMarketData();
    const regime = market.regime || 'Neutral';
    const vix = market.vix?.value ?? 'N/A';

    const scoringSystem = `You pick the 3 stocks most likely to make a significant move in the next few hours. Think like a trader, not an analyst.

MARKET CONTEXT MATTERS:
- In Risk Off (high VIX, fear): favor defensive catalysts, earnings beats from quality names, and high-short-interest squeezes. Downgrades hit harder.
- In Risk On (low VIX, greed): favor momentum plays, growth earnings beats, and upgrade cascades. The market rewards risk-taking.
- In Neutral: pure catalyst quality matters most — biggest surprise vs expectations wins.

PRIORITIZE:
1. Earnings with a clear beat or miss (especially EPS surprises >10%) — these move immediately
2. Analyst upgrades/downgrades from top-tier firms (Goldman, Morgan Stanley, JP Morgan) — price target changes >15% from current price
3. Breaking news with direct revenue/regulatory impact — not vague "industry trends"
4. Names with real trading volume — avoid anything nobody can actually trade

AVOID:
- Micro-caps under $500M market cap with no options chain
- Two stocks from the same sector (diversify the picks)
- Stale catalysts (old news repackaged)

Return ONLY a JSON array of the candidate numbers (1-indexed) in order of expected move magnitude. Example: [3, 1, 7]`;
    const ctrl = new AbortController();
    const tm = setTimeout(() => ctrl.abort(), 30000);
    let msg;
    try {
      msg = await anthropic.messages.create({
        model: MODEL_HAIKU,
        max_tokens: 300,
        system: [{ type: 'text', text: scoringSystem, cache_control: { type: 'ephemeral' } }],
        messages: [{ role: 'user', content: `Current market: ${regime} regime, VIX ${vix}.\nPick the top 3 catalysts for the "${dropLabel}" drop from these candidates:\n${candidateStr}` }],
      }, { signal: ctrl.signal });
    } finally { clearTimeout(tm); }

    const text = msg.content[0].text;
    const match = text.match(/\[[\d\s,]+\]/);
    if (match) {
      const picks = JSON.parse(match[0]);
      const selected = picks
        .filter(i => i >= 1 && i <= candidates.length)
        .map(i => candidates[i - 1])
        .slice(0, 3);
      if (selected.length > 0) return selected;
    }
  } catch (err) {
    console.error(`[Catalyst] AI scoring failed for ${dropId}:`, err.message);
  }

  // Fallback: sort by strength and take top 3
  return candidates.sort((a, b) => b.strength - a.strength).slice(0, 3);
}

/**
 * Enrich selected stocks with price data and analyst upgrades.
 */
async function enrichStocks(stocks) {
  if (!stocks.length) return stocks;

  const tickers = stocks.map(s => s.ticker);

  // Get price snapshots and analyst data in parallel
  const [priceData, ...upgradeResults] = await Promise.all([
    getSnapshots(tickers).catch(() => ({})),
    ...tickers.map(t => isFinnhubAvailable() ? getUpgradeDowngrade(t).catch(() => []) : Promise.resolve([])),
  ]);

  for (let i = 0; i < stocks.length; i++) {
    const stock = stocks[i];
    const snap = priceData[stock.ticker];
    const upgrades = upgradeResults[i] || [];

    // Add price data
    stock.price = snap?.price ?? null;
    stock.changePct = snap?.changePercent ? parseFloat(snap.changePercent.toFixed(2)) : null;
    stock.volume = snap?.volume ?? null;

    // Stack catalyst signals for flame rating
    let signals = 1; // base signal from the catalyst itself
    if (upgrades.length > 0) {
      signals++;
      const recent = upgrades[0];
      if (!stock.analystAction) {
        stock.analystAction = `${recent.action} by ${recent.company}: ${recent.fromGrade || ''} → ${recent.toGrade || ''}`.trim();
      }
    }
    if (stock.catalystType.includes('earnings') && stock.strength >= 2) signals++;
    if (Math.abs(stock.changePct ?? 0) > 5) signals++; // big mover already

    stock.flameRating = Math.min(3, signals); // cap at 3 flames

    // Get a ticker-specific news headline if we don't have a good detail yet
    if (stock.catalystType === 'news' && isFinnhubAvailable()) {
      try {
        const tickerNews = await getTickerNews(stock.ticker, 1);
        if (tickerNews.length > 0 && tickerNews[0].title) {
          stock.detail = tickerNews[0].title;
          stock.newsSource = tickerNews[0].source;
        }
      } catch {}
    }
  }

  return stocks;
}

/**
 * Generate a complete catalyst drop.
 */
async function generateDrop(dropId) {
  const drop = DROP_SCHEDULE.find(d => d.id === dropId);
  if (!drop) return null;

  console.log(`[Catalyst] Generating ${drop.label} drop...`);

  const { candidates, quality, sources } = await gatherCandidates(dropId);
  if (candidates.length === 0) {
    console.log(`[Catalyst] No candidates found for ${dropId}`);
    return { stocks: [], label: drop.label, generatedAt: new Date().toISOString(), dropId, dataQuality: quality };
  }

  const top3 = await scoreCandidates(candidates, dropId, drop.label);
  const enriched = await enrichStocks(top3);

  const result = {
    stocks: enriched,
    label: drop.label,
    dropId,
    generatedAt: new Date().toISOString(),
    generatedAtET: getETTime().timeStr,
    dataQuality: quality, // 'full', 'partial', or 'degraded'
    dataSources: sources,
  };

  console.log(`[Catalyst] ${drop.label}: ${enriched.map(s => s.ticker).join(', ') || 'empty'}`);
  return result;
}

/**
 * Generate end-of-day recap showing how picks performed.
 */
async function generateRecap() {
  const allPicks = [];
  for (const [dropId, drop] of Object.entries(catalystDrops)) {
    if (!drop?.stocks?.length) continue;
    for (const stock of drop.stocks) {
      allPicks.push({ ...stock, dropLabel: drop.label, dropTime: drop.generatedAtET });
    }
  }

  if (allPicks.length === 0) return null;

  // Get current prices for all picks
  const tickers = allPicks.map(p => p.ticker);
  let currentPrices = {};
  try {
    currentPrices = await getSnapshots(tickers);
  } catch {}

  const recap = allPicks.map(pick => {
    const current = currentPrices[pick.ticker];
    const currentPrice = current?.price ?? pick.price;
    const currentChange = current?.changePercent ?? pick.changePct;

    return {
      ticker: pick.ticker,
      dropLabel: pick.dropLabel,
      dropTime: pick.dropTime,
      catalystLabel: pick.catalystLabel,
      priceAtPick: pick.price,
      currentPrice,
      changeSincePick: pick.price && currentPrice ? parseFloat(((currentPrice - pick.price) / pick.price * 100).toFixed(2)) : null,
      dayChange: currentChange ? parseFloat(currentChange.toFixed(2)) : null,
    };
  });

  return {
    stocks: recap,
    generatedAt: new Date().toISOString(),
    totalPicks: recap.length,
    winners: recap.filter(r => (r.dayChange ?? 0) > 0).length,
    losers: recap.filter(r => (r.dayChange ?? 0) < 0).length,
  };
}

/**
 * Background catalyst scheduler — checks every minute if a drop is due.
 */
async function catalystScheduler() {
  try {
    const et = getETTime();

    // Skip weekends
    if (et.dayOfWeek === 0 || et.dayOfWeek === 6) return;

    // Midnight reset
    if (catalystDay && catalystDay !== et.dateStr) {
      console.log('[Catalyst] New day — resetting drops');
      catalystDrops = {};
      recapData = null;
    }
    catalystDay = et.dateStr;

    // Check each drop. Two firing modes:
    //   1. On-time: within 5 min of the scheduled drop window (the original path).
    //   2. Catch-up: drop time has passed but we haven't generated it yet AND
    //      we're still within today's catch-up window (before 6pm ET). Covers
    //      the case where the host laptop slept through a scheduled time —
    //      data sources (today's earnings + breaking news) are still relevant
    //      so a late drop is way better than no drop. The scheduler runs every
    //      60s and the loop limits to ONE drop per tick to avoid bursting the
    //      Claude API on wake-up after a long sleep.
    const CATCHUP_CUTOFF_MIN = 18 * 60;       // 6pm ET — after this, give up
    const currentMinutes = et.hour * 60 + et.minute;
    let firedThisTick = false;

    for (const drop of DROP_SCHEDULE) {
      if (firedThisTick) break;
      if (catalystDrops[drop.id]) continue;

      const dropMinutes = drop.hour * 60 + drop.minute;
      const onTime = currentMinutes >= dropMinutes && currentMinutes <= dropMinutes + 5;
      const catchUp = currentMinutes > dropMinutes + 5 && currentMinutes <= CATCHUP_CUTOFF_MIN;

      if (!onTime && !catchUp) continue;

      if (catchUp) {
        console.log(`[Catalyst] Catch-up firing for ${drop.id} (scheduled ${drop.hour}:${String(drop.minute).padStart(2, '0')}, now ${et.timeStr})`);
      }

      const result = await generateDrop(drop.id);
      if (result) {
        catalystDrops[drop.id] = result;
        await persistCatalystData();
        firedThisTick = true;
      }
    }

    // Generate recap at 4:05 PM ET (after market close)
    if (et.hour === 16 && et.minute >= 5 && et.minute <= 10 && !recapData) {
      recapData = await generateRecap();
      await persistCatalystData();
    }

  } catch (err) {
    console.error('[Catalyst] Scheduler error:', err.message);
  }
}

/**
 * Persist catalyst data to Supabase for recovery after restart.
 */
async function persistCatalystData() {
  try {
    const payload = JSON.stringify({
      drops: catalystDrops,
      recap: recapData,
      day: catalystDay,
    });
    const cacheKey = 'catalyst_watch_today';
    const { data: existing } = await supabase.from('ai_cache').select('id').eq('cache_key', cacheKey).maybeSingle();
    if (existing) {
      await supabase.from('ai_cache').update({ result: payload, created_at: new Date().toISOString() }).eq('id', existing.id);
    } else {
      await supabase.from('ai_cache').insert({ cache_key: cacheKey, result: payload, created_at: new Date().toISOString() });
    }
  } catch (err) {
    console.error('[Catalyst] Persist failed:', err.message);
  }
}

/**
 * Load cached catalyst data on startup.
 */
async function loadCachedData() {
  try {
    const { data: cached } = await supabase.from('ai_cache').select('*').eq('cache_key', 'catalyst_watch_today').maybeSingle();
    if (cached?.result) {
      const parsed = JSON.parse(cached.result);
      const today = new Date().toISOString().split('T')[0];
      if (parsed.day === today) {
        catalystDrops = parsed.drops || {};
        recapData = parsed.recap || null;
        catalystDay = parsed.day;
        const dropCount = Object.keys(catalystDrops).length;
        console.log(`[Catalyst] Loaded cached data — ${dropCount} drops from today`);
      }
    }
  } catch {}
}

/**
 * Start the catalyst scheduler.
 * Runs every 60 seconds to check if a drop is due.
 */
export function startCatalystScheduler() {
  console.log('[Catalyst] Starting catalyst watch scheduler...');

  loadCachedData().then(() => {
    // Initial check after 10 second delay
    setTimeout(() => {
      catalystScheduler();
      // Then check every 60 seconds
      setInterval(catalystScheduler, 60 * 1000);
    }, 10000);
  });
}

/**
 * Manually trigger a drop generation (for testing or on-demand).
 */
export async function triggerDrop(dropId) {
  const result = await generateDrop(dropId);
  if (result) {
    catalystDrops[dropId] = result;
    await persistCatalystData();
  }
  return result;
}

// ============ API ROUTES ============

// GET /api/social/catalyst — main endpoint for catalyst watch tab
router.get('/', requireAuth, rateLimit(20), async (req, res) => {
  try {
    const et = getETTime();
    const activeDropIds = getActiveDropIds(et.hour, et.minute);

    // Build drops array with timing info
    const drops = DROP_SCHEDULE.map(drop => {
      const isActive = activeDropIds.includes(drop.id);
      const data = catalystDrops[drop.id] || null;
      const dropTime = `${drop.hour > 12 ? drop.hour - 12 : drop.hour}:${String(drop.minute).padStart(2, '0')} ${drop.hour >= 12 ? 'PM' : 'AM'}`;

      return {
        id: drop.id,
        label: drop.label,
        scheduledTime: dropTime,
        isActive,       // Has this time passed today?
        isGenerated: !!data,  // Do we have data for this drop?
        stocks: data?.stocks ?? [],
        generatedAt: data?.generatedAt ?? null,
        generatedAtET: data?.generatedAtET ?? null,
      };
    });

    // Calculate next drop time
    const nextDrop = DROP_SCHEDULE.find(d => !activeDropIds.includes(d.id));
    let nextDropIn = null;
    if (nextDrop) {
      const dropMinutes = nextDrop.hour * 60 + nextDrop.minute;
      const currentMinutes = et.hour * 60 + et.minute;
      nextDropIn = dropMinutes - currentMinutes;
    }

    res.json({
      drops,
      recap: recapData,
      nextDropIn,    // minutes until next drop (null if all done)
      currentTimeET: et.timeStr,
      isWeekend: et.dayOfWeek === 0 || et.dayOfWeek === 6,
      disclaimer: 'Catalyst data for informational purposes only. Not financial advice.',
    });
  } catch (err) {
    console.error('[Catalyst] API error:', err);
    res.status(500).json({ error: 'Catalyst watch unavailable' });
  }
});

// POST /api/social/catalyst/generate — manually trigger a drop (for testing)
router.post('/generate', requireAuth, rateLimit(3), async (req, res) => {
  try {
    const { dropId } = req.body;
    if (!DROP_SCHEDULE.find(d => d.id === dropId)) {
      return res.status(400).json({ error: 'Invalid drop ID. Use: premarket, midday, powerhour' });
    }

    const result = await triggerDrop(dropId);
    res.json({ drop: result });
  } catch (err) {
    console.error('[Catalyst] Manual generation error:', err);
    res.status(500).json({ error: 'Generation failed' });
  }
});

// POST /api/social/catalyst/recap — manually trigger recap (for testing)
router.post('/recap', requireAuth, rateLimit(3), async (req, res) => {
  try {
    recapData = await generateRecap();
    if (recapData) await persistCatalystData();
    res.json({ recap: recapData });
  } catch (err) {
    console.error('[Catalyst] Recap error:', err);
    res.status(500).json({ error: 'Recap generation failed' });
  }
});

export default router;
